compile: appendMeMore.c verifyFileDescriptors.c fileDescriptorDuplicate.c
	gcc -Wall appendMeMore.c -o appendMeMore & gcc -Wall verifyFileDescriptors.c -o verifyFileDescriptors & gcc -Wall fileDescriptorDuplicate.c -o fileDescriptorDuplicate

clean:
	rm appendMeMore & rm verifyFileDescriptors & rm fileDescriptorDuplicate
	rm *.txt & rm f1 & rm f2